// app/lib/coaches.ts

export const coaches = [
  {
    id: "linet",
    name: "LINET M.",
    role: "HIIT & Conditioning",
    base: "Highway Mall",
    img: "/media/coach-linet.webp",
    classes: 847,
    rating: 4.9,
    bio: "LINETis a certified HIIT specialist with over 10 years of experience transforming lives through high-intensity training. Her sessions are legendary in the Nairobi fitness community for pushing members to their absolute limits while maintaining perfect form and safety. With a background in competitive athletics, LINETbrings elite-level programming that delivers real results.",
    philosophy: "I believe every workout should leave you better than you came in — stronger, faster, and more confident. My mission is to help you discover what you're truly capable of.",
    specialties: [
      "High-Intensity Interval Training",
      "Metabolic Conditioning",
      "Bootcamp Style Training",
      "Cardio Blast Sessions",
      "Competition Prep",
    ],
    certifications: [
      "NASM-CPT (Certified Personal Trainer)",
      "HIIT Specialist Certification",
      "Precision Nutrition Level 1",
      "First Aid & CPR Certified",
    ],
    experience: "10+ years",
    achievements: [
      "Trained 800+ members to their fitness goals",
      "Former national track athlete",
      "Featured in Fitness Kenya Magazine",
      "Created WW's signature HIIT program",
    ],
    schedule: [
      { day: "Monday", time: "6:00 AM", class: "Hardcore HIIT", duration: "45 min" },
      { day: "Monday", time: "5:30 PM", class: "Evening Burn", duration: "45 min" },
      { day: "Wednesday", time: "6:00 AM", class: "Cardio Blast", duration: "45 min" },
      { day: "Friday", time: "6:00 AM", class: "Friday Finisher", duration: "45 min" },
      { day: "Saturday", time: "8:00 AM", class: "Weekend Warrior", duration: "60 min" },
    ],
  },
  {
    id: "barrack",
    name: "BARRACK H.",
    role: "Strength & Power",
    base: "Highway Mall",
    img: "/media/coach-barrack.webp",
    classes: 612,
    rating: 4.8,
    bio: "Barrack specializes in strength training and powerlifting with a track record of building serious muscle and strength safely. With a background in competitive powerlifting, he brings elite-level programming that combines science-based training with practical coaching. Whether you're a beginner or advanced lifter, Barrack designs programs that deliver measurable strength gains.",
    philosophy: "Strength isn't just physical — it's mental. Every rep, every set builds not just muscle, but confidence and discipline that carries into every area of life.",
    specialties: [
      "Powerlifting (Squat, Bench, Deadlift)",
      "Olympic Weightlifting",
      "Hypertrophy Training",
      "Strength Programming",
      "Form & Technique Coaching",
    ],
    certifications: [
      "CSCS (Certified Strength & Conditioning Specialist)",
      "USAW Level 2 (Olympic Lifting)",
      "Precision Nutrition Coach",
      "FMS Level 1 (Functional Movement)",
    ],
    experience: "8+ years",
    achievements: [
      "Competed in national powerlifting championships",
      "Coached members to 600+ total increases",
      "Kenya Powerlifting Federation certified coach",
      "Designed WW's strength progression system",
    ],
    schedule: [
      { day: "Tuesday", time: "7:00 AM", class: "Strength Foundations", duration: "60 min" },
      { day: "Thursday", time: "7:00 AM", class: "Power Hour", duration: "60 min" },
      { day: "Thursday", time: "6:00 PM", class: "Evening Strength", duration: "60 min" },
      { day: "Saturday", time: "9:00 AM", class: "Olympic Lifting", duration: "75 min" },
    ],
  },
  {
    id: "vincent",
    name: "VINCENT J.",
    role: "Zen & Flow",
    base: "Highway Mall",
    img: "/media/coach-vincent.webp",
    classes: 1204,
    rating: 5.0,
    bio: "Vincent  brings calm to the chaos with her yoga and mindfulness practice. A former professional ballet dancer, she combines movement, breath work, and meditation to help members find their center. Her classes blend vinyasa flow, restorative yoga, and meditation techniques that reduce stress and improve flexibility. Vincent 's gentle yet powerful approach has helped over 1,000 members discover the mind-body connection.",
    philosophy: "Yoga isn't about touching your toes — it's about what you learn on the way down. Every breath, every movement is an opportunity to come home to yourself.",
    specialties: [
      "Vinyasa Flow Yoga",
      "Restorative Yoga",
      "Meditation & Mindfulness",
      "Breath Work (Pranayama)",
      "Mobility & Flexibility",
    ],
    certifications: [
      "RYT-500 (Registered Yoga Teacher)",
      "Meditation Teacher Certification",
      "Reiki Level II Practitioner",
      "Yin Yoga Specialist",
    ],
    experience: "12+ years",
    achievements: [
      "Taught over 1,200 yoga classes",
      "Former professional ballet dancer",
      "Founded Nairobi Mindfulness Collective",
      "Yoga retreat facilitator (Bali, India)",
    ],
    schedule: [
      { day: "Monday", time: "5:30 PM", class: "Vinyasa Flow", duration: "60 min" },
      { day: "Wednesday", time: "6:30 AM", class: "Morning Flow", duration: "60 min" },
      { day: "Wednesday", time: "7:00 PM", class: "Zen Meditation", duration: "45 min" },
      { day: "Friday", time: "6:00 PM", class: "Wind Down Flow", duration: "60 min" },
      { day: "Sunday", time: "10:00 AM", class: "Sunday Reset", duration: "75 min" },
    ],
  },
  {
    id: "daniel",
    name: "DANIEL O.",
    role: "Cardio & Endurance",
    base: "Highway Mall",
    img: "/media/coach-daniel.webp",
    classes: 538,
    rating: 4.7,
    bio: "Daniel is an endurance athlete who's completed multiple marathons and triathlons across East Africa. He designs cardio programs that build stamina, speed, and mental toughness. His expertise in running mechanics and endurance training helps members of all levels — from complete beginners to competitive runners — achieve their cardiovascular goals safely and effectively.",
    philosophy: "Endurance is earned one step at a time. Whether you're training for a 5K or a marathon, consistency and smart programming beat talent every time.",
    specialties: [
      "Running Technique & Form",
      "Endurance Training",
      "Cycling & Spin Classes",
      "Triathlon Preparation",
      "Heart Rate Zone Training",
    ],
    certifications: [
      "RRCA Running Coach",
      "USA Triathlon Level 1 Coach",
      "Cycling Instructor Certification",
      "Sports Nutrition Specialist",
    ],
    experience: "7+ years",
    achievements: [
      "Completed 8 marathons (PR: 2:47:32)",
      "Ironman 70.3 finisher",
      "Coached 100+ members to race PRs",
      "Run club founder (500+ members)",
    ],
    schedule: [
      { day: "Tuesday", time: "6:00 AM", class: "Endurance Run", duration: "60 min" },
      { day: "Thursday", time: "6:00 AM", class: "Tempo Training", duration: "45 min" },
      { day: "Thursday", time: "6:00 PM", class: "Spin Class", duration: "45 min" },
      { day: "Saturday", time: "6:30 AM", class: "Long Run Club", duration: "90 min" },
    ],
  },
  {
    id: "hamisi",
    name: "HAMISI J.",
    role: "Recovery & Mobility",
    base: "Highway Mall",
    img: "/media/coach-hamisi.webp",
    classes: 423,
    rating: 4.9,
    bio: "Hamisi is a licensed physical therapist specializing in recovery, injury prevention, and restoring movement quality. Her classes focus on mobility, flexibility, and movement patterns that keep you training pain-free. With a background in sports rehabilitation, Hamisi helps members recover faster, move better, and prevent injuries before they happen.",
    philosophy: "Recovery isn't rest — it's active restoration. The work you do between workouts is just as important as the workout itself.",
    specialties: [
      "Mobility Training",
      "Injury Prevention",
      "Movement Assessment",
      "Myofascial Release",
      "Corrective Exercise",
    ],
    certifications: [
      "DPT (Doctor of Physical Therapy)",
      "FMS Level 2 (Functional Movement Systems)",
      "SFMA Certified",
      "Yoga Alliance RYT-200",
    ],
    experience: "9+ years",
    achievements: [
      "Rehabilitated 500+ athletes",
      "Sports team physical therapist",
      "Published in Kenya PT Journal",
      "Created WW's mobility screening protocol",
    ],
    schedule: [
      { day: "Monday", time: "7:00 PM", class: "Mobility Flow", duration: "45 min" },
      { day: "Wednesday", time: "7:00 PM", class: "Recovery Session", duration: "45 min" },
      { day: "Friday", time: "6:00 PM", class: "Stretch & Release", duration: "45 min" },
      { day: "Sunday", time: "11:00 AM", class: "Active Recovery", duration: "60 min" },
    ],
  },
  {
    id: "robert",  // Must match folder name and image
    name: "ROBERT M.",
    role: "Strength & Conditioning",
    base: "Highway Mall",
    img: "/media/coach-robert.webp",
    classes: 592,
    rating: 4.8,
    bio: "Robert is a certified strength and conditioning specialist with a passion for building functional strength. His programs combine powerlifting foundations with athletic conditioning to create well-rounded, resilient athletes. With years of experience training everyone from beginners to competitive lifters, Robert brings expert programming and motivational coaching to every session.",
    philosophy: "Strength is built through consistency, not intensity alone. Every rep, every set, every session builds the foundation for what's possible.",
    specialties: [
      "Strength Training",
      "Athletic Conditioning",
      "Powerlifting Technique",
      "Progressive Overload Programming",
      "Form & Movement Quality",
    ],
    certifications: [
      "CSCS (Certified Strength & Conditioning Specialist)",
      "NASM-CPT",
      "Precision Nutrition Level 1",
      "FMS Level 1",
    ],
    experience: "9+ years",
    achievements: [
      "Trained 500+ members to strength PRs",
      "Regional powerlifting competitor",
      "Featured in Fitness East Africa Magazine",
      "Designed WW's beginner strength program",
    ],
    schedule: [
      { day: "Monday", time: "6:00 AM", class: "Morning Strength", duration: "60 min" },
      { day: "Wednesday", time: "6:00 PM", class: "Evening Power", duration: "60 min" },
      { day: "Friday", time: "6:00 AM", class: "Full Body Friday", duration: "60 min" },
      { day: "Saturday", time: "10:00 AM", class: "Weekend Warrior", duration: "75 min" },
    ],
  },

  // NEW COACH 2: WEKESA
  {
    id: "wekesa",
    name: "WEKESA K.",
    role: "Cardio & Endurance",
    base: "Highway Mall",
    img: "/media/coach-wekesa.webp",
    classes: 734,
    rating: 4.9,
    bio: "Wekesa is an endurance athlete and running coach who has competed in marathons across Kenya and East Africa. He brings elite-level cardiovascular training to members of all fitness levels. His classes focus on building aerobic capacity, improving running mechanics, and developing mental toughness. Whether you're training for your first 5K or your tenth marathon, Wekesa designs programs that deliver results.",
    philosophy: "Endurance isn't just physical capacity—it's mental resilience. The finish line starts in your mind.",
    specialties: [
      "Long-Distance Running",
      "Interval Training",
      "Running Mechanics & Form",
      "VO2 Max Development",
      "Race Preparation",
    ],
    certifications: [
      "RRCA Running Coach",
      "Athletics Kenya Certified",
      "Sports Nutrition Specialist",
      "CPR & First Aid Certified",
    ],
    experience: "11+ years",
    achievements: [
      "Completed 12 marathons (PR: 2:34:18)",
      "Coached 200+ members to race PRs",
      "Founded Nairobi Run Club",
      "Featured coach in Runner's World Kenya",
    ],
    schedule: [
      { day: "Tuesday", time: "5:45 AM", class: "Tempo Run", duration: "60 min" },
      { day: "Thursday", time: "6:00 AM", class: "Interval Training", duration: "45 min" },
      { day: "Saturday", time: "6:00 AM", class: "Long Run Club", duration: "90 min" },
      { day: "Sunday", time: "7:00 AM", class: "Recovery Run", duration: "45 min" },
    ],
  },

  // NEW COACH 3: MAX
  {
    id: "max",
    name: "MAX O.",
    role: "Functional Fitness & Mobility",
    base: "Highway Mall",
    img: "/media/coach-max.webp",
    classes: 468,
    rating: 4.7,
    bio: "Max specializes in functional fitness and mobility training that translates directly to real-world movement and daily life. With a background in physical therapy and corrective exercise, Max helps members move better, reduce pain, and prevent injuries. His classes blend functional strength work with mobility drills and movement pattern training to build bodies that are both strong and resilient.",
    philosophy: "Move well first, then move often. Quality movement is the foundation of everything else.",
    specialties: [
      "Functional Movement Patterns",
      "Mobility & Flexibility Training",
      "Corrective Exercise",
      "Injury Prevention",
      "Core Stability",
    ],
    certifications: [
      "FMS (Functional Movement Systems) Level 2",
      "SFMA Certified",
      "NASM-CES (Corrective Exercise Specialist)",
      "TRX Suspension Training Certified",
    ],
    experience: "7+ years",
    achievements: [
      "Rehabilitated 300+ members from chronic pain",
      "Created WW's mobility assessment protocol",
      "Published in Kenya PT Journal",
      "Workshop instructor for movement quality",
    ],
    schedule: [
      { day: "Monday", time: "7:00 PM", class: "Functional Strength", duration: "45 min" },
      { day: "Wednesday", time: "6:30 AM", class: "Mobility Flow", duration: "45 min" },
      { day: "Friday", time: "7:00 PM", class: "Movement Prep", duration: "45 min" },
      { day: "Sunday", time: "9:00 AM", class: "Active Recovery", duration: "60 min" },
    ],
  },
  // NEW COACH 3: HASSAN
  {
    id: "hassan",
    name: "HASSAN.",
    role: "Functional Fitness & Mobility",
    base: "Highway Mall",
    img: "/media/coach-hassan.webp",
    classes: 468,
    rating: 4.7,
    bio: "Max specializes in functional fitness and mobility training that translates directly to real-world movement and daily life. With a background in physical therapy and corrective exercise, Max helps members move better, reduce pain, and prevent injuries. His classes blend functional strength work with mobility drills and movement pattern training to build bodies that are both strong and resilient.",
    philosophy: "Move well first, then move often. Quality movement is the foundation of everything else.",
    specialties: [
      "Functional Movement Patterns",
      "Mobility & Flexibility Training",
      "Corrective Exercise",
      "Injury Prevention",
      "Core Stability",
    ],
    certifications: [
      "FMS (Functional Movement Systems) Level 2",
      "SFMA Certified",
      "NASM-CES (Corrective Exercise Specialist)",
      "TRX Suspension Training Certified",
    ],
    experience: "7+ years",
    achievements: [
      "Rehabilitated 300+ members from chronic pain",
      "Created WW's mobility assessment protocol",
      "Published in Kenya PT Journal",
      "Workshop instructor for movement quality",
    ],
    schedule: [
      { day: "Monday", time: "7:00 PM", class: "Functional Strength", duration: "45 min" },
      { day: "Wednesday", time: "6:30 AM", class: "Mobility Flow", duration: "45 min" },
      { day: "Friday", time: "7:00 PM", class: "Movement Prep", duration: "45 min" },
      { day: "Sunday", time: "9:00 AM", class: "Active Recovery", duration: "60 min" },
    ],
  },
];
